services:
    postgres:
        image: postgres:18
        healthcheck:
          test: ["CMD-SHELL", "pg_isready -U postgres"]
          interval: 5s
          retries: 5
        volumes:
         - /root/pgdata:/var/lib/postgresql/18/data
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=123
          - POSTGRES_DB=apidata
        ports:
          - "5432:5432"

    migrator:
        build:
          context: ./Server
          dockerfile: Dockerfile.sdk
        depends_on:
          postgres:
              condition: service_healthy

    server:
        build: ./Server
        depends_on:
          postgres:
            condition: service_healthy
        ports:
         - "5001:5001"
